name: Github action autodeploy container to VM
on:
  push:
    branches:
      - main

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Listing File on Runner
        run: ls -la

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: rudicatsmile2/simplelandingpage:${{ github.run_number }}

  deploy-container:
    runs-on: ubuntu-latest
    needs: test-build-push
    steps:
      - name: Deploy COntainer on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_TOKEN }}
            docker pull rudicatsmile2/simplelandingpage:${{ github.run_number }}
            docker rm -f simplelandingpage-app 
            docker run --name simplelandingpage-app -p 80:80 rudicatsmile2/simplelandingpage:${{ github.run_number }}
