name: Github action autodeploy container to VM
on:
  push:
    branches:
      - main

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Listing File on Runner
        run: ls -la

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: rudicatsmile2/simplelandingpage:${{ github.run_number }}
